# Generated by Django 5.2.13 on 2026-04-10 05:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rehearsal", "Rehearsal"),
                            ("performance", "Performance"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("timezone", models.CharField(max_length=64)),
                ("is_all_day", models.BooleanField(default=False)),
                (
                    "google_calendar_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "member_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="members.memberprofile",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "event__start_at",
                    "member_profile__last_name",
                    "member_profile__first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EventAudience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all_members", "All members"),
                            ("group", "Group"),
                            ("selected_members", "Selected members"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="events.event",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_audiences",
                        to="members.group",
                    ),
                ),
                (
                    "member_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_audiences",
                        to="members.memberprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("maybe", "Maybe"),
                            ("no_response", "No response"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.event",
                    ),
                ),
                (
                    "member_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "event__start_at",
                    "member_profile__last_name",
                    "member_profile__first_name",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["organization", "start_at"], name="event_org_start_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization", "type", "start_at"], name="event_org_type_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["event", "status"], name="attendance_event_status_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["member_profile", "event"], name="attendance_member_event_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                fields=("event", "member_profile"), name="unique_attendance_per_event_member"
            ),
        ),
        migrations.AddIndex(
            model_name="eventaudience",
            index=models.Index(fields=["event", "audience_type"], name="event_audience_type_idx"),
        ),
        migrations.AddIndex(
            model_name="eventaudience",
            index=models.Index(fields=["group"], name="event_audience_group_idx"),
        ),
        migrations.AddIndex(
            model_name="eventaudience",
            index=models.Index(fields=["member_profile"], name="event_audience_member_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventaudience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("audience_type", "all_members"),
                        ("group__isnull", True),
                        ("member_profile__isnull", True),
                    ),
                    models.Q(
                        ("audience_type", "group"),
                        ("group__isnull", False),
                        ("member_profile__isnull", True),
                    ),
                    models.Q(
                        ("audience_type", "selected_members"),
                        ("group__isnull", True),
                        ("member_profile__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_event_audience_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("audience_type", "all_members")),
                fields=("event",),
                name="unique_all_members_audience_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("audience_type", "group")),
                fields=("event", "group"),
                name="unique_group_audience_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("audience_type", "selected_members")),
                fields=("event", "member_profile"),
                name="unique_selected_member_audience_per_event",
            ),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["event", "status"], name="rsvp_event_status_idx"),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["member_profile", "event"], name="rsvp_member_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="rsvp",
            constraint=models.UniqueConstraint(
                fields=("event", "member_profile"), name="unique_rsvp_per_event_member"
            ),
        ),
    ]
