# Generated by Django 5.2.13 on 2026-04-11 01:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.organization')),
            ],
            options={
                'ordering': ['-published_at', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_campaigns', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience_type', models.CharField(choices=[('all_members', 'All members'), ('group', 'Group'), ('selected_members', 'Selected members')], max_length=32)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='communications.announcement')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_audiences', to='members.group')),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_audiences', to='members.memberprofile')),
            ],
            options={
                'ordering': ['audience_type', 'group__name', 'member_profile__last_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('member_profile__isnull', True)), fields=('announcement', 'audience_type'), name='unique_announcement_all_members_audience'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('announcement', 'audience_type', 'group'), name='unique_announcement_group_audience'), models.UniqueConstraint(condition=models.Q(('member_profile__isnull', False)), fields=('announcement', 'audience_type', 'member_profile'), name='unique_announcement_member_audience')],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('member_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', to='members.memberprofile')),
                ('message_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.messagecampaign')),
            ],
            options={
                'ordering': ['member_profile__last_name', 'member_profile__first_name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('message_campaign', 'member_profile'), name='unique_campaign_member_recipient')],
            },
        ),
    ]
