# Generated by Django 5.2.13 on 2026-04-10 04:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("section", "Section"),
                            ("committee", "Committee"),
                            ("ensemble", "Ensemble"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "voice_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soprano", "Soprano"),
                            ("alto", "Alto"),
                            ("tenor", "Tenor"),
                            ("bass", "Bass"),
                            ("baritone", "Baritone"),
                            ("mezzo_soprano", "Mezzo-soprano"),
                            ("contralto", "Contralto"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("joined_at", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "email"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="members.group",
                    ),
                ),
                (
                    "member_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "group__name",
                    "member_profile__last_name",
                    "member_profile__first_name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("organization", "type", "name"), name="unique_group_name_per_org_and_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "email"), name="unique_member_email_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("organization", "user"),
                name="unique_member_user_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "member_profile"), name="unique_group_member_assignment"
            ),
        ),
    ]
